# C言語で記述したバージョンのテスト
all:
	(cd TaC.Opt; make)
	(cd VM.Opt; make)
	(cd IM.Opt; make)
	(cd C.Opt; make)
	(cd C.RTC; make)

# C--言語で記述したバージョンのテスト
cmm:
	(cd TaC.Opt; make cmm)
	(cd VM.Opt; make cmm)
	(cd IM.Opt; make cmm)
	(cd C.Opt; make cmm)
	(cd C.RTC; make cmm)

asm:
	(cd TaC.Opt; make asm)
	(cd VM.Opt; make asm)
	(cd IM.Opt; make asm)
	(cd C.Opt; make asm)
	(cd C.RTC; make asm)

clean:
	(cd TaC.Opt; make clean)
	(cd VM.Opt; make clean)
	(cd IM.Opt; make clean)
	(cd C.Opt; make clean)
	(cd C.RTC; make clean)

