static char a=97;
static char b=10;
static char c=9;
static char d=13;
static char e=18;
static char f=83;
static char g=39;
static char h=34;
static char i=92;
static char j=59;
#define _cmm_0S "abcd"
static char *o=_cmm_0S;
#define _cmm_1S "abcd\n"
static char *p=_cmm_1S;
#define _cmm_2S "abcd\t"
static char *q=_cmm_2S;
#define _cmm_3S "abcd\r"
static char *r=_cmm_3S;
#define _cmm_4S "ab\022 34cd"
static char *s=_cmm_4S;
#define _cmm_5S "\012x34cd"
static char *t=_cmm_5S;
#define _cmm_6S "ab\'cd"
static char *u=_cmm_6S;
#define _cmm_7S "ab\"cde"
static char *v=_cmm_7S;
#define _cmm_8S "ab\\cde"
static char *w=_cmm_8S;
#define _cmm_9S "ab;cde"
static char *x=_cmm_9S;
