#!/bin/sh

INCDIR=/usr/local/cmmInclude
LIBDIR=/usr/local/cmmLib

CFLAGS="-funsigned-char -Wno-parentheses-equality -Wno-tautological-compare \
   -Wno-pointer-sign -Wno-int-conversion -Wno-unused-value -Wno-unsequenced \
   -Wno-dangling-else -include ${LIBDIR}/wrapper.h"

CPPFLAGS="-std=c99 -nostdinc -DC"

myname=`basename $0`
exefile="a.out"
sflag="no"
cflag="no"
eflag="no"
while [ $# -gt 0 ]; do
    case "$1" in
	-o) exefile=$2;  shift; shift;;
        -S) sflag="yes"; shift;;
        -c) cflag="yes"; shift;;
        -E) eflag="yes"; shift;;
	-D*)flg=`echo $1 | sed -e 's/"/\\\\"/g'`
	    CPPFLAGS="${CPPFLAGS} \"${flg}\""; shift;;
        -*) echo  "\"${myname}\" is the C-- compiler driver."     1>&2
            echo  "syntax: ${myname} [switches] <c-- source> ..." 1>&2
            echo  "     switches are :"                           1>&2
            echo  "       -o exec  executable file name"          1>&2
            echo  "       -S       leave .c file"                 1>&2
            echo  "       -c       leave .o file"                 1>&2
            echo  "       -E       run the preprocessor stage"    1>&2
            echo  "       -Dxx=yy  define xx as yy"               1>&2
            echo  "       -h       print this message"            1>&2
            exit 1;;
        *)  break;;     # terminate while loop
    esac
done


if [ $# -le 0 ]; then
    echo "${myname} : no input files." 1>&2
    exit 1
fi

objs=""
tmps=""
while [ $# -gt 0 ]; do
    j=`basename $1`
    name=`expr "${j}" : '\(.*\)\.[^.]*'`
    ext=`expr "${j}" : '.*\(\.[^.]*\)'`
    case "${ext}" in
        *.cmm)
	    if [ "${eflag}" == "yes" ]; then
		eval cc -E ${CPPFLAGS} -I${INCDIR} -I${LIBDIR} - < $1
	    else
		eval cc -E ${CPPFLAGS} -I${INCDIR} -I${LIBDIR} - < $1 |
		c-c-- -O > ${name}.c
		if [ "${sflag}" != "yes" ]; then
                    cc -c ${CFLAGS} -I${LIBDIR} ${name}.c;
                    rm -f ${name}.c
                    objs="${objs} ${name}.o"
                    tmps="${tmps} ${name}.o"
		fi
	    fi ;;
        *.c)
            if [ "${eflag}" != "yes" -a "${sflag}" != "yes" ]; then
                cc -c ${CFLAGS} -I${LIBDIR} ${name}.c;
                objs="${objs} ${name}.o"
                tmps="${tmps} ${name}.o"
            fi ;;
        *.o)
            objs="${objs} ${name}.o" ;;
        *)
            echo "${myname} : ${i} : illegal extension." 1>&2
            rm -f ${tmps}
            exit 1;;
    esac
    shift
done

if [ "${eflag}" != "yes" -a "${sflag}" != "yes" -a "${cflag}" != "yes" ]; then
    cc -o ${exefile} -I${LIBDIR} ${LIBDIR}/wrapper.c ${objs} 
    rm -f ${tmps}
fi

exit 0
