#!/bin/sh

function error {
  eval  "$@"
  rm -f ${tmps}
  exit 1
}

INCDIR="-I/usr/local/cmmInclude -I/usr/local/cmmLib"
LIBDIR=/usr/local/cmmLib

CFLAGS="-g -O0 \
   -funsigned-char -Wno-parentheses-equality -Wno-tautological-compare \
   -Wno-pointer-sign -Wno-int-conversion -Wno-unused-value -Wno-unsequenced \
   -Wno-dangling-else -include stdio.h -include ${LIBDIR}/wrapper.h"

CPPFLAGS="-xc++ -nostdinc -nostdlibinc -nobuiltininc -DC"

myname=`basename $0`
exefile="a.out"
sflag="no"
cflag="no"
eflag="no"
incdir=""
while [ $# -gt 0 ]; do
    case "$1" in
        -o) exefile=$2;  shift; shift;;
        -S) sflag="yes"; shift;;
        -c) cflag="yes"; shift;;
        -E) eflag="yes"; shift;;
        -nostdinc) INCDIR=""; shift;;
        -I) incdir="$incdir -I$2" shift; shift;;
        -I*)incdir="$incdir $1" shift;;
        -D*)flg=`echo $1 | sed -e 's/"/\\\\"/g'`
            CPPFLAGS="${CPPFLAGS} \"${flg}\""; shift;;
        -*) echo  "\"${myname}\" is the C-- compiler driver."             1>&2
            echo  "syntax: ${myname} [switches] <c-- source> ..."         1>&2
            echo  "     switches are :"                                   1>&2
            echo  "       -o exec  executable file name"                  1>&2
            echo  "       -S       leave .c file"                         1>&2
            echo  "       -c       leave .o file"                         1>&2
            echo  "       -E       run the preprocessor stage"            1>&2
            echo  "       -nostdinc Disable standard include directories" 1>&2
            echo  "       -I dir    Add incude directory"                 1>&2
            echo  "       -Dxx=yy  define xx as yy"                       1>&2
            echo  "       -h       print this message"                    1>&2
            exit 1;;
        *)  break;;     # terminate while loop
    esac
done


if [ $# -le 0 ]; then
    echo "${myname} : no input files."                            1>&2
    exit 1
fi

objs=""
tmps=""
while [ $# -gt 0 ]; do
    j=`basename $1`
    name=`expr "${j}" : '\(.*\)\.[^.]*'`
    ext=`expr "${j}" : '.*\(\.[^.]*\)'`
    case "${ext}" in
        *.cmm)
            if [ "${eflag}" == "yes" ]; then
                eval cpp ${CPPFLAGS} ${INCDIR} ${incdir} $1 || error
            else
                eval cpp ${CPPFLAGS} ${INCDIR} ${incdir} $1 \
                  > $$.tmp || error rm $$.tmp
                c-c-- -O $$.tmp > ${name}.c || error rm $$.tmp ${name}.c
                rm $$.tmp

                if [ "${sflag}" != "yes" ]; then
                    objs="${objs} ${name}.o"
                    tmps="${tmps} ${name}.o"
                    cc -c ${CFLAGS} -I${LIBDIR} ${name}.c || error rm ${name}.c
                    rm -f ${name}.c
                fi
            fi ;;
        *.c)
            if [ "${eflag}" != "yes" -a "${sflag}" != "yes" ]; then
                objs="${objs} ${name}.o"
                tmps="${tmps} ${name}.o"
                cc -c ${CFLAGS} -I${LIBDIR} ${name}.c || error
            fi ;;
        *.o)
            objs="${objs} ${name}.o" ;;
        *)
            echo "${myname} : ${j} : illegal extension." 1>&2
            rm -f ${tmps}
            exit 1;;
    esac
    shift
done

if [ "${eflag}" != "yes" -a "${sflag}" != "yes" -a "${cflag}" != "yes" ]; then
    cc ${CFLAGS} -o ${exefile} -I${LIBDIR} ${LIBDIR}/wrapper.c ${objs} 
    rm -f ${tmps}
fi

exit 0
