#!/bin/sh

INCDIR=/usr/local/cmmInclude
LIBDIR=/usr/local/cmmLib

myname=`basename $0`
exefile="a.out"
sflag="no"
cflag="no"
eflag="no"
while [ $# -gt 0 ]; do
    case "$1" in
        -E) eflag="yes"; shift;;
	-D*)flg=`echo $1 | sed -e 's/"/\\\\"/g'`
	    CPPFLAGS="${CPPFLAGS} \"${flg}\""; shift;;
        -*) echo  "\"${myname}\" is the C-- compiler driver."     1>&2
            echo  "syntax: ${myname} [switches] <c-- source> ..." 1>&2
            echo  "     switches are :"                           1>&2
            echo  "       -E       run the preprocessor stage"    1>&2
            echo  "       -Dxx=yy  define xx as yy"               1>&2
            echo  "       -h       print this message"            1>&2
            exit 1;;
        *)  break;;     # terminate while loop
    esac
done

if [ $# -le 0 ]; then
    echo "${myname} : no input files." 1>&2
    exit 1
fi

while [ $# -gt 0 ]; do
    j=`basename $1`
    name=`expr "${j}" : '\(.*\)\.[^.]*'`
    ext=`expr "${j}" : '.*\(\.[^.]*\)'`
    case "${ext}" in
        *.cmm)
	    if [ "${eflag}" == "yes" ]; then
		eval cc -E ${CPPFLAGS} -I${INCDIR} -I${LIBDIR} - < $1
	    else
		eval cc -E ${CPPFLAGS} -I${INCDIR} -I${LIBDIR} - < $1 |
		vm-c-- -O > ${name}.v
	    fi ;;
        *)
            echo "${myname} : ${i} : illegal extension." 1>&2
            rm -f ${tmps}
            exit 1;;
    esac
    shift
done

exit 0
