all:
	(cd TaC.Opt; make)
	(cd VM.Opt; make)
#	(cd H8.Opt; make)
#	(cd TaC.noOpt; make)
#	(cd VM.noOpt; make)
#	(cd H8.noOpt; make)

asm:
	(cd TaC.Opt; make asm)
	(cd VM.Opt; make asm)
#	(cd H8.Opt; make asm)
#	(cd TaC.noOpt; make asm)
#	(cd VM.noOpt; make asm)
#	(cd H8.noOpt; make asm)

clean:
	(cd TaC.Opt; make clean)
	(cd VM.Opt; make clean)
#	(cd H8.Opt; make clean)
#	(cd TaC.noOpt; make clean)
#	(cd VM.noOpt; make clean)
#	(cd H8.noOpt; make clean)

